services: # コンポースするサービスたち

    go-api-srv: # サービス名
        build: # ビルド設定
            target: deploy-final
        image: juninry/go-api:latest # image name
        ports: # ホストマシンのポートとコンテナのポートをマッピング 
            - "4561:4561"
