services:  # コンポースするサービスたち

    go-api-srv: # サービスの名前
        container_name: juninry-go-api  # コンテナ名
        build:  # ビルド設定
            context: ./go-api/  # ビルドプロセスが実行されるパス 
            dockerfile: Dockerfile  # Dockerfileのパス
        environment: # 環境変数
            TZ: ${TZ}
        networks: # 定義したネットワークを利用
            - db_net # dbに接続するネットワーク

    mysql-db-srv: # サービスの名前
        container_name: juninry-mysql-db # コンテナ名
        image: mysql:latest # pullするイメージ
        volumes: # ボリュームの保持
            - ./mysql-db/db_data:/var/lib/mysql # DBデータをホストに保持
        environment: # 環境変数
            TZ: ${TZ}
        env_file: # 環境変数のまとまりをファイルに記述して渡す
            - .env.mysql-db
        restart: always # コンテナの再起動
        networks: # 定義したネットワークを利用
            - db_net # dbに接続するネットワーク

networks: # ネットワークの定義
    db_net: # dbに接続するネットワーク
