services: # コンポースするサービスたち

    go-api-srv: # サービス名
        container_name: juninry_dep_go-api  # コンテナ名
        build: # ビルド設定
            target: deploy-final
        image: juninry/go-api:latest # image name\
        volumes: # ボリュームの保持
            - ../services/mysql-db/db_data:/var/lib/mysql # DBデータをホストに保持
        ports: # ホストマシンのポートとコンテナのポートをマッピング 
            - "${API_DEPLOY_HOST_PORT}:4561"

    mysql-db-srv: # サービス名
        container_name: juninry_dep_mysql-db # コンテナ名
